language: rust
sudo: false

# run builds for all the trains (and more)
rust:
  - 1.0.0
  - 1.2.0
  - 1.4.0
  - 1.5.0
  - 1.6.0
  - 1.7.0
  - stable
  - nightly
branches:
  only:
    - master

# load travis-cargo
before_script:
  - |
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH

# the main build
script:
  - |
      travis-cargo build &&
      travis-cargo test &&
      travis-cargo doc
after_success:
  # upload the documentation (GH_TOKEN from env)
  - travis-cargo --only nightly doc-upload

env:
  global:
    # override the default `--features unstable` used for the nightly branch (optional)
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
