[package]
name = "rand_derive"
version = "0.1.0"
authors = ["bluss"]
license = "MIT/Apache-2.0"

[dependencies]
parse-macros = "0.1"
parse-generics-shim = "0.1"

[dev-dependencies]
custom_derive = "0.1.5"
rand = "0.3"
